dataset_location: ./data/csv_files/direct_grid_few_shot_number_pipe_3.5.csv
batch_size: 1
prompt_start_location: prompting_classes/prompt_zero_shot.txt
prompt_delimiter:  # If nothing there this means space
max_return_length: 4096
temperature: 0.1
model_id: meta-llama/Llama-2-13b-chat-hf
output_path: ./experiments_results/zero_shot_prompting.csv